### ISSUE TITLE
报错了 铁汁 明明有类啊 怎么导入不进来

### ISSUE THREAD

**Issue by 897180673** [YYC572652645/QCoolPage#2]
![image](https://user-images.githubusercontent.com/19344284/87679465-cca7b000-c7ae-11ea-9c35-c3d7a8b6a8a9.png)

**Comment by YYC572652645** [comment]
这是什么平台啊？我使用的是windows+Qt5.6

**Comment by 897180673** [comment]
mac平台, 找到原因了,因为上面的#include 里面的路径 linux是 /   上面报错是\  改一下就好了
